var Artists = {
	Gustavho: function(){
		return "<div class='row'><div class='col-md-6'><img src='img/artists/GustavoDescripcion.jpg' class='img-responsive' /></div> <div class='col-md-6'>Gustavho Bacilo, nacido en 1991 Cali Colombia, llega al público con sus innovadores ritmos diferenciándose por su gran oído musical. <br /><br /> Inicia su carrera musical en 2007 colaborando con diferentes estudios de producción. Poco después entra a formar parte de Star Flow Entretaiment, productora de música urbana underground, de la mano de Bloke18 & Gansta Flow, lanzando temas de mucho éxito. <br /><br /> A finales del 2008 influenciado por deejays y productores a un alto nivel nacional, extiende sus conocimientos y empieza a explorar a fondo los sonidos mas electrónicos. <br /><br /> Este joven deejay, abre camino a su gran gusto musical dando un toque de su estilo, mezclando electrónica y percusión, sonidos que definen a un continente como lo son África y América. En 2009 logra colaborar en eventos importantes de su país y en ese mismo año viaja a Barcelona para continuar con sus estudios. Iniciando el 2011, lanza sus producciones con dos etiquetas muy importantes a nivel mundial como son: Dephone recording & Koleto Beatz, trabajando actualmente para dichos sellos. Hasta el día de hoy Gustavho a participado en salas importantes en la ciudad de Barcelona como: Row14, La Cova, Atic..;sus cercanías y en la zona de Valencia. Compartiendo cartel con deejays como: Paco Osuna, Luciano, Alex Under, Valentinno Kanziani, Agatha Pher…</div><div>";
	},
	Krusound: function(){
		return "<div class='row'><div class='col-md-6'><img src='img/artists/krusoundDescripcion.png' class='img-responsive' /></div> <div class='col-md-6'>Dúo formado por Endika Esteban (1989) y Francesc Font (1988),  que inician su carrera en 2009 en Barcelona, España. Queriendo transmitir sus conocimientos e inquietudes musicales. Para crear una música seria y profunda pero a la vez desenfada y divertida.<br /><br /> A parte de la música electrónica, Kru-Sound se identifica por su versatilidad en diferentes aspectos de la música, colaborando así con diferentes tipos de espectáculos tales como:      <br /> ⦁	Desarrollar un proyecto paralelo de música urbana con El Pauako y Bcn Studios.<br />⦁	Creación de música para el espectáculo SKRIBO, de la compañía teatral “Els Comediants”.<br /><br />Presentando siempre un formato diferente al convencional, para desarrollar una sesión en directo con sonidos propios.<br /><br />Actualmente, preparan nuevos proyectos junto a Gustavho Bacilo, Juan Termes y Agatha Pher y otros en los que se incluyen lanzamientos discográficos, presentando en diferentes tiendas formato digital y vinilo.  También preparan la organización de diferentes eventos para mostrar su propuesta musical.</div><div>";
	},
	German: function(){
		return "<div class='row'><div class='col-md-6'><img src='img/artists/germanDescripcion.png' class='img-responsive' /></div> <div class='col-md-6'>Empieza su carrera musical en el 2004, Canet de Mar (Actualmente es su lugar de residencia y el asentamiento de su estudio).<br /><br /> Hablar de Germán Luque, es hablar de avance y progreso dentro de la escena Musical electrónica, hombre de nuevas tecnologías, siempre buscando un selecto y avanzado estilo musical fuera de lo común. <br /><br />Es el factor que más le destaca a este carismático joven, que se abre las puertas del mundo de la producción y en poco tiempo, lanza sus primeros trabajos por destacados sellos en el mercado mundial digital.<br /><br /> En el año 2012 German y sus compañeros, crean la distinguida marca Barcelonesa Door67 Recordings que ayudo a solidificar su carrera musical.Su empeño y constáncia, hacen de él, un artista innovador y eficaz consiguiendo con todo, una gran efectividad en la pista, por todo ello su carrera actualmente, esta en plena evolución tanto a nivel de Dj como a nivel de productor.</div><div>";
	},
	Jandro: function(){
		return '<h1>Send Demo</h1><div class="row_form_general"><p>Looking to send a demo to Door67 for consideration? Please send an email with a private STREAMABLE & DOWNLOADABLE link to your music at: <label>demos@door67.com</label></p><img id="imgMoon" src="https://scontent-a-cdg.xx.fbcdn.net/hphotos-xpa1/v/t1.0-9/1560496_689809134396522_1495269487_n.jpg?oh=c6dc63a85c3c1168f4755de1b6ca1e52&oe=543DF375" alt="logo" width="390px"/></div>';
	},
	Lexlay: function(){
		return '<h1>Send Demo</h1><div class="row_form_general"><p>Looking to send a demo to Door67 for consideration? Please send an email with a private STREAMABLE & DOWNLOADABLE link to your music at: <label>demos@door67.com</label></p><img id="imgMoon" src="https://scontent-a-cdg.xx.fbcdn.net/hphotos-xpa1/v/t1.0-9/1560496_689809134396522_1495269487_n.jpg?oh=c6dc63a85c3c1168f4755de1b6ca1e52&oe=543DF375" alt="logo" width="390px"/></div>';
	},
	Cesar: function(){
		return '<h1>Send Demo</h1><div class="row_form_general"><p>Looking to send a demo to Door67 for consideration? Please send an email with a private STREAMABLE & DOWNLOADABLE link to your music at: <label>demos@door67.com</label></p><img id="imgMoon" src="https://scontent-a-cdg.xx.fbcdn.net/hphotos-xpa1/v/t1.0-9/1560496_689809134396522_1495269487_n.jpg?oh=c6dc63a85c3c1168f4755de1b6ca1e52&oe=543DF375" alt="logo" width="390px"/></div>';
	},
	Agatha: function(){
		return '<h1>Send Demo</h1><div class="row_form_general"><p>Looking to send a demo to Door67 for consideration? Please send an email with a private STREAMABLE & DOWNLOADABLE link to your music at: <label>demos@door67.com</label></p><img id="imgMoon" src="https://scontent-a-cdg.xx.fbcdn.net/hphotos-xpa1/v/t1.0-9/1560496_689809134396522_1495269487_n.jpg?oh=c6dc63a85c3c1168f4755de1b6ca1e52&oe=543DF375" alt="logo" width="390px"/></div>';
	}
};